### PR TITLE
Craft 5 Support

### PR DESCRIPTION
**Pull request by tomkiss**
- Initial support in a v3.0.0 version for Craft 5.

### CODE REVIEW

**Comment by sgtpenguin** [comment]
It would be great to get craft 5 support for this plugin.  One of the last preventing an upgrade.  Please let me know if I can help.

**Comment by knufri** [comment]
+1 
@jalendport please merge the PR 🙏

**Comment by tomkiss** [comment]
I dropped @jalendport an email to see if there's any insight he might be able to offer as to updating the plugin. I also emailed Steadfast in May but got no reply.

How about @btbunze, are you able to help at all with this plugin and its maintenance?

If it's abandoned, it would be helpful to flag it as such in the Craft Plugin store.
Or, if permitted, I could re-publish as a Craft 5 plugin but move the management over to the community.

**Comment by jalendport** [comment]
Thanks a bunch for the PR @tomkiss; I ended up rolling my own commits for a couple different reasons.

**Pull request closed without merging**
